[package]
name = "expm"
version = "0.1.0"
authors = ["elsuizo <mnoblia@disroot.org>"]
edition = "2018"

[dependencies]
ndarray = "0.11"
ndarray-linalg = {version = "0.9", features = ["openblas"]}
num = "*"
